name: Do Things Every 5 Hours
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:    
    - cron:  '0 */5 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository _
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      - run: GET https://varatija.000webhostapp.com/officemiwebhostingtry1.php
      - run: GET https://fordevelopmio.webcindario.com/officemiwebhostingtry1.php
      - run: sleep 35
      - run: GET https://fordevelopmio.webcindario.com/officemanvgsm1.php
      - run: sleep 25
      - run: GET https://varatija.000webhostapp.com/officeinfyspoporte1.php
      - run: sleep 10
      - run: GET https://fordevelopmio.webcindario.com/manuel281.php
      - run: GET https://committed-lanes.000webhostapp.com/officemanvgsm_w1.php
      - run: sleep 45
      - run: GET https://committed-lanes.000webhostapp.com/manuel281.php
      - run: sleep 35
      - run: GET https://committed-lanes.000webhostapp.com/lostones11_w.php
      - run: sleep 15
      - run: GET https://committed-lanes.000webhostapp.com/homeworkutils_w.php?check_email=true
      - run: sleep 25
      - run: GET https://committed-lanes.000webhostapp.com/zilev.php?check_email=true
      - run: sleep 55
      - run: GET https://committed-lanes.000webhostapp.com/anibla.php?check_email=true
      - run: sleep 15
      - run: GET https://committed-lanes.000webhostapp.com/enyavdp.php?check_email=true
      - run: sleep 25
      - run: GET https://committed-lanes.000webhostapp.com/herbertd.php?check_email=true
      - run: sleep 35
      - run: GET https://fordevelopmio.webcindario.com/ailadaleunam1.php
      - run: GET https://committed-lanes.000webhostapp.com/mannew.php?check_email=true
      - run: sleep 45
      - run: GET https://committed-lanes.000webhostapp.com/testerforhome.php?check_email=true
      - run: sleep 55
      - run: GET https://committed-lanes.000webhostapp.com/ludgerjanssen.php?check_email=true
      - run: sleep 65
      - run: GET https://committed-lanes.000webhostapp.com/randynewman.php?check_email=true
      - run: sleep 45
      - run: GET https://committed-lanes.000webhostapp.com/sangrilah.php?check_email=true
      - run: sleep 55
      - run: GET https://committed-lanes.000webhostapp.com/copiaseguridad.php?check_email=true
      - run: GET https://fordevelopmio.webcindario.com/r00w.php?check_email=true
